# Generated by Django 5.2.2 on 2025-06-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SweetTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
    ]
