# Generated by Django 5.2.2 on 2025-06-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0003_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
