# Generated by Django 5.2.2 on 2025-06-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0004_order_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
