# Generated by Django 5.2.2 on 2025-06-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0006_ordermeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Juice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFried',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('fried_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweet.frieditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fried_items', to='sweet.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderJuice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('juice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweet.juice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juices', to='sweet.order')),
            ],
        ),
    ]
